In [68]:
import requests
import pandas as pd
import json
import os
import numpy as np
from time import sleep
from scipy.stats import norm
import warnings

# Configurações de exibição e avisos
pd.options.display.max_rows = 100
pd.options.display.max_columns = 100
warnings.filterwarnings('ignore')

In [69]:
ativos = ['ABEV3', 'B3SA3', 'BBAS3', 'BBSE3', 'EGIE3', 'FLRY3',
          'HYPE3', 'ITSA4', 'KLBN11', 'LEVE3', 'PETR4', 'TAEE11',
          'UNIP6', 'VALE3', 'RADL3']

In [70]:
# ---------------------------------------------------
# 2. DOWNLOAD E ATUALIZAÇÃO (CORREÇÃO JSON)
# ---------------------------------------------------
if not os.path.exists("dbJson"):
    os.makedirs("dbJson")

def atualizarDados(ativo):
    url = f"https://storage.googleapis.com/api-cdn-eaglesystem/api/{ativo.upper()}"
    try:
        response = requests.get(url, timeout=10)
        if response.status_code != 200:
            return f"{ativo}: erro HTTP {response.status_code}"
        
        # Validação de conteúdo JSON para evitar erro 'Expecting value'
        content = response.text.strip()
        if not (content.startswith('{') or content.startswith('[')):
            return f"{ativo}: Erro - Conteúdo não é JSON válido"

        dados = response.json()
        with open(f"dbJson/{ativo}.json", "w", encoding="utf-8") as arq:
            json.dump(dados, arq, indent=2)
        return f"{ativo}: atualizado"
    except Exception as e:
        return f"{ativo}: erro -> {e}"

for ativo in ativos:
    print(atualizarDados(ativo))

ABEV3: atualizado
B3SA3: atualizado
BBAS3: atualizado
BBSE3: atualizado
EGIE3: atualizado
FLRY3: atualizado
HYPE3: atualizado
ITSA4: atualizado
KLBN11: atualizado
LEVE3: atualizado
PETR4: atualizado
TAEE11: atualizado
UNIP6: atualizado
VALE3: atualizado
RADL3: atualizado

In [71]:
# ---------------------------------------------------
# 3. PROCESSAMENTO DOS DADOS (DATAFRAME)
# ---------------------------------------------------
def dataFrameUnico(ativo):
    with open(f"dbJson/{ativo}.json", "r", encoding="utf-8") as arq:
        dados = json.load(arq)

    preco_atual = dados["asset"]["close"]
    linhas = []

    for serie in dados["series"]:
        vencimento = serie.get("due_date")
        dias = serie.get("days_to_maturity")

        for strike in serie["strikes"]:
            strike_price = strike["strike"]
            for tipo in ["call", "put"]:
                opt = strike[tipo]
                if opt:
  linhas.append({
                        "ativo": ativo, 
                        "symbol": opt["symbol"],
                        "categoria": tipo.upper(), 
                        "preco_atual": preco_atual,
                        "strike": strike_price, 
                        "bid": opt["bid"], 
                        "ask": opt["ask"], 
                        "volume": opt["volume"],
                        "maturity_type": opt["maturity_type"],
                        "moneyness": opt["bs"]["moneyness"],
                        "price": opt["bs"]["price"],
                        "delta": opt["bs"]["delta"], 
                        "gamma": opt["bs"]["gamma"], 
                        "vega": opt["bs"]["vega"],
                        "theta": opt["bs"]["theta"],
                        "rho": opt["bs"]["rho"],
                        "vol": opt["bs"]["volatility"], 
                        "poe": opt["bs"]["poe"],
                        "dias": dias,
                        "vencimento": vencimento,
                    })
    return pd.DataFrame(linhas)

todos = []
for ativo in ativos:

    df = dataFrameUnico(ativo)
    todos.append(df)


df_final = pd.concat(todos, ignore_index=True)

IndentationError: unindent does not match any outer indentation level (<string>, line 20)

In [ ]:
df_final

,ativo,symbol,categoria,preco_atual,strike,bid,ask,volume,maturity_type,moneyness,price,delta,gamma,vega,theta,rho,vol,poe,dias,vencimento
0,ABEV3,ABEVG960W2,CALL,15.87,9.56,0.00,0.0,0,AMERICAN,ITM,6.3326,1.000000,0.000000,0.000000,-0.005639,0.001514,0.000,100.00,4,2026-07-10
1,ABEV3,ABEVS960W2,PUT,15.87,9.56,0.00,0.0,0,EUROPEAN,OTM,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.00,4,2026-07-10
2,ABEV3,ABEVG980W2,CALL,15.87,9.76,0.00,0.0,0,AMERICAN,ITM,6.1331,1.000000,0.000000,0.000000,-0.005757,0.001546,0.000,100.00,4,2026-07-10
3,ABEV3,ABEVS980W2,PUT,15.87,9.76,0.00,0.0,0,EUROPEAN,OTM,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.00,4,2026-07-10
4,ABEV3,ABEVG100W2,CALL,15.87,9.96,0.00,0.0,0,AMERICAN,ITM,5.9335,1.000000,0.000000,0.000000,-0.005875,0.001577,0.000,100.00,4,2026-07-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21767,RADL3,RADLT200,PUT,16.78,19.29,0.00,0.0,0,EUROPEAN,ITM,2.5076,-0.390834,0.054769,0.068388,0.000622,-0.102170,33.406,55.59,284,2027-08-20
21768,RADL3,RADLL220,CALL,16.78,21.83,0.35,0.0,200,AMERICAN,OTM,2.8264,0.554463,0.049734,0.079813,-0.008132,0.093821,32.902,36.82,365,2027-12-17
21769,RADL3,RADLX220,PUT,16.78,21.83,0.00,0.0,0,EUROPEAN,ITM,3.6389,-0.445537,0.049734,0.079813,0.002270,-0.160991,43.258,63.18,365,2027-12-17
21770,RADL3,RADLL250,CALL,16.78,24.83,0.00,0.0,0,AMERICAN,OTM,2.0582,0.446322,0.049748,0.079835,-0.007515,0.078664,32.285,27.14,365,2027-12-17
21771,RADL3,RADLX250,PUT,16.78,24.83,0.00,0.0,0,EUROPEAN,ITM,5.2883,-0.553678,0.049748,0.079835,0.004317,-0.211165,29.305,72.86,365,2027-12-17

In [ ]:
puts = df_final[df_final["categoria"] == "PUT"].copy()


puts["retorno"] = (puts["bid"] / (puts["strike"] - puts['bid'])) * 100
puts["retorno_mes"] = puts["retorno"] * (30 / puts["dias"].replace(0, 1))
puts["dist_strike"] = ((puts["strike"] / puts["preco_atual"]) - 1) * 100


# Ranking e Score
filtro_put = puts[

    (puts['dias'].between(15, np.inf)) &
    (puts['dist_strike'] <= 0) &
    (puts['retorno_mes'] >= 0.95)


].copy()

if not filtro_put.empty:
    filtro_put['score'] = (
        filtro_put['dist_strike'].rank(ascending=True) * 1 +
        filtro_put['retorno_mes'].rank(ascending=False) * 4 +
        filtro_put['retorno'].rank(ascending=False) * 3
    )
    print("\n--- MELHORES OPÇÕES DE VENDA DE PUT ---")

    display(filtro_put[

        [
            'ativo', 'symbol', 'categoria','moneyness' , 'strike', 'preco_atual',
            'dist_strike', 'bid', 'ask',
            'volume', 'delta', 'theta', 'vol', 'poe',  'retorno', 'retorno_mes',
            'dias', 'vencimento', 'score',
        ]

    ].sort_values('score').head(30))

--- MELHORES OPÇÕES DE VENDA DE PUT ---

,ativo,symbol,categoria,moneyness,strike,preco_atual,dist_strike,bid,ask,volume,delta,theta,vol,poe,retorno,retorno_mes,dias,vencimento,score
21281,RADL3,RADLT165,PUT,OTM,16.43,16.78,-2.085816,0.68,0.70,27500,-0.360475,-0.009391,38.185,41.58,4.317460,3.809524,34,2026-08-21,103.0
21279,RADL3,RADLT162,PUT,OTM,16.18,16.78,-3.575685,0.58,0.61,400,-0.321585,-0.009265,39.351,37.50,3.717949,3.280543,34,2026-08-21,116.0
2195,B3SA3,B3SAV15,PUT,OTM,14.26,14.56,-2.060440,0.82,0.96,200,-0.335420,-0.003813,43.604,40.83,6.101190,2.542163,72,2026-10-16,143.5
1873,B3SA3,B3SAT144,PUT,OTM,14.26,14.56,-2.060440,0.51,0.52,31300,-0.353861,-0.007217,32.161,40.43,3.709091,3.272727,34,2026-08-21,153.5
1875,B3SA3,B3SAT150,PUT,ATM,14.46,14.56,-0.686813,0.59,0.61,53200,-0.393626,-0.007189,36.043,44.54,4.253785,3.753340,34,2026-08-21,157.5
1871,B3SA3,B3SAT141,PUT,OTM,14.01,14.56,-3.777473,0.42,0.43,14300,-0.305621,-0.007084,36.894,35.36,3.090508,2.726919,34,2026-08-21,168.0
7621,EGIE3,EGIET317,PUT,OTM,31.75,32.30,-1.702786,1.05,1.27,2000,-0.357047,-0.014211,35.181,40.35,3.420195,3.017820,34,2026-08-21,181.5
7623,EGIE3,EGIET322,PUT,ATM,32.25,32.30,-0.154799,1.29,1.54,2500,-0.405790,-0.014009,37.062,45.37,4.166667,3.676471,34,2026-08-21,185.5
7619,EGIE3,EGIET319,PUT,OTM,31.50,32.30,-2.476780,0.95,1.17,400,-0.333195,-0.014172,34.902,37.87,3.109656,2.743814,34,2026-08-21,187.0
13599,PETR4,PETRV437,PUT,OTM,36.80,37.89,-2.876748,1.69,1.75,400,-0.281265,-0.005631,35.117,33.07,4.813443,2.005601,72,2026-10-16,195.0
13595,PETR4,PETRV388,PUT,OTM,36.30,37.89,-4.196358,1.51,1.57,200,-0.249510,-0.005691,35.240,29.64,4.340328,1.808470,72,2026-10-16,206.0
13603,PETR4,PETRV384,PUT,OTM,37.30,37.89,-1.557139,1.88,1.94,0,-0.314387,-0.005443,36.834,36.60,5.307736,2.211557,72,2026-10-16,207.0
13607,PETR4,PETRV389,PUT,ATM,37.80,37.89,-0.237530,2.09,2.14,0,-0.348605,-0.005121,37.246,40.21,5.852702,2.438626,72,2026-10-16,213.0
617,ABEV3,ABEVT157,PUT,ATM,15.75,15.87,-0.756144,0.49,0.51,8300,-0.373569,-0.005252,28.527,41.28,3.211009,2.833243,34,2026-08-21,221.0
7617,EGIE3,EGIET312,PUT,OTM,31.25,32.30,-3.250774,0.85,0.96,300,-0.309816,-0.014043,34.471,35.41,2.796053,2.467105,34,2026-08-21,227.0
8825,HYPE3,HYPET205,PUT,OTM,20.32,20.74,-2.025072,0.57,0.60,8000,-0.352291,-0.009871,28.166,40.12,2.886076,2.546538,34,2026-08-21,244.0
1869,B3SA3,B3SAT139,PUT,OTM,13.76,14.56,-5.494505,0.34,0.36,3400,-0.259759,-0.006777,37.561,30.45,2.533532,2.235469,34,2026-08-21,256.0
12603,PETR4,PETRT389,PUT,ATM,37.86,37.89,-0.079177,1.17,1.19,123000,-0.395904,-0.011303,27.670,43.37,3.188880,2.813717,34,2026-08-21,256.0
12601,PETR4,PETRT387,PUT,ATM,37.61,37.89,-0.738981,1.07,1.09,58900,-0.369837,-0.011528,27.752,40.70,2.928298,2.583792,34,2026-08-21,264.5
13591,PETR4,PETRV383,PUT,OTM,35.80,37.89,-5.515967,1.35,1.41,6600,-0.219371,-0.005635,36.224,26.33,3.918723,1.632801,72,2026-10-16,267.0
3561,BBAS3,BBAST197,PUT,ATM,19.65,19.73,-0.405474,0.56,0.58,33900,-0.361229,-0.003840,27.426,39.01,2.933473,2.588359,34,2026-08-21,267.5
17785,VALE3,VALET779,PUT,ATM,77.96,78.38,-0.535851,2.19,2.21,46600,-0.382206,-0.026029,27.224,42.19,2.890326,2.550288,34,2026-08-21,281.0
615,ABEV3,ABEVT155,PUT,OTM,15.50,15.87,-2.331443,0.40,0.41,24400,-0.315891,-0.005299,30.188,35.30,2.649007,2.337359,34,2026-08-21,282.0
12599,PETR4,PETRT384,PUT,OTM,37.36,37.89,-1.398786,0.98,0.99,42000,-0.344187,-0.011652,27.910,38.05,2.693788,2.376872,34,2026-08-21,300.0
8117,FLRY3,FLRYT154,PUT,ATM,15.48,15.60,-0.769231,0.41,0.47,0,-0.363223,-0.004306,32.133,39.81,2.720637,2.400562,34,2026-08-21,307.0
7615,EGIE3,EGIET307,PUT,OTM,30.75,32.30,-4.798762,0.68,0.85,26700,-0.264846,-0.013532,34.352,30.63,2.261390,1.995344,34,2026-08-21,319.5
17783,VALE3,VALET774,PUT,OTM,77.46,78.38,-1.173769,1.99,2.01,51000,-0.358515,-0.026319,26.936,39.75,2.636809,2.326596,34,2026-08-21,325.0
3559,BBAS3,BBAST195,PUT,OTM,19.40,19.73,-1.672580,0.47,0.48,6200,-0.300428,-0.004013,27.730,32.75,2.482831,2.190734,34,2026-08-21,340.0
12597,PETR4,PETRT382,PUT,OTM,37.11,37.89,-2.058591,0.89,0.90,146300,-0.319070,-0.011677,28.552,35.45,2.457206,2.168123,34,2026-08-21,340.5
14025,PETR4,PETRX399,PUT,OTM,36.60,37.89,-3.404592,1.93,3.48,0,-0.252747,-0.003021,35.655,31.32,5.566772,1.439683,116,2026-12-18,348.0

In [ ]:
calls = df_final[df_final["categoria"] == "CALL"].copy()

# Retorno apenas do prêmio
calls["retorno"] = (calls["bid"] / calls["preco_atual"]) * 100

# Retorno mensalizado
calls["retorno_mes"] = calls["retorno"] * (30 / calls["dias"].replace(0, 1))

# Distância do strike
calls["dist_strike"] = (
    (calls["strike"] / calls["preco_atual"]) - 1
) * 100


# -----------------------------
# FILTRO
# -----------------------------

filtro_call = calls[

    (calls["dias"] >= 15) &
    (calls["dist_strike"].between(0,np.inf)) &
    (calls["retorno_mes"] >= 0.70) &


].copy()

# -----------------------------
# SCORE
# -----------------------------

if not filtro_call.empty:

    filtro_call["score"] = (

        filtro_call["retorno_mes"].rank(ascending=False) * 4 +
        filtro_call["dist_strike"].rank(ascending=False) * 3 +
        filtro_call["volume"].rank(ascending=False) * 2 +
        filtro_call["theta"].rank(ascending=False) * 1

    )

    print("\n--- MELHORES OPÇÕES DE VENDA DE CALL ---")

    display(

        filtro_call[
            [
                "ativo", "symbol", "categoria", "moneyness", "strike",
                "preco_atual", "dist_strike", "bid", "ask", "volume", "delta",
                "theta", "vol", "poe", "retorno", "retorno_mes", "dias", "vencimento",
                "score",

            ]
        ]
        .sort_values("score")
        .head(30)

    )

--- MELHORES OPÇÕES DE VENDA DE CALL ---

,ativo,symbol,categoria,moneyness,strike,preco_atual,dist_strike,bid,ask,volume,delta,theta,vol,poe,retorno,retorno_mes,dias,vencimento,score
1884,B3SA3,B3SAH159,CALL,OTM,15.71,14.56,7.898352,0.42,0.43,23500,0.361150,-0.013481,34.980,31.28,2.884615,2.545249,34,2026-08-21,251.0
1888,B3SA3,B3SAH167,CALL,OTM,16.21,14.56,11.332418,0.29,0.31,11400,0.277037,-0.011710,36.720,23.45,1.991758,1.757434,34,2026-08-21,272.0
1882,B3SA3,B3SAH157,CALL,OTM,15.46,14.56,6.181319,0.50,0.51,24600,0.407333,-0.014217,34.925,35.68,3.434066,3.030058,34,2026-08-21,299.5
1886,B3SA3,B3SAH162,CALL,OTM,15.96,14.56,9.615385,0.35,0.37,5600,0.317589,-0.012636,35.003,27.19,2.403846,2.121041,34,2026-08-21,318.5
626,ABEV3,ABEVH177,CALL,OTM,17.00,15.87,7.120353,0.33,0.34,69400,0.335039,-0.011619,27.314,29.87,2.079395,1.834760,34,2026-08-21,333.0
3570,BBAS3,BBASH212,CALL,OTM,20.90,19.73,5.930056,0.44,0.46,53000,0.324924,-0.011568,25.742,29.80,2.230106,1.967741,34,2026-08-21,370.0
3572,BBAS3,BBASH215,CALL,OTM,21.15,19.73,7.197162,0.36,0.38,55500,0.270936,-0.010343,25.937,24.63,1.824633,1.609970,34,2026-08-21,380.0
1880,B3SA3,B3SAH154,CALL,OTM,15.21,14.56,4.464286,0.59,0.61,31600,0.455624,-0.014814,35.277,40.36,4.052198,3.575469,34,2026-08-21,381.0
21292,RADL3,RADLH180,CALL,OTM,17.93,16.78,6.853397,0.62,0.63,2100,0.402354,-0.017412,38.384,34.76,3.694875,3.260184,34,2026-08-21,383.0
622,ABEV3,ABEVH165,CALL,OTM,16.50,15.87,3.969754,0.49,0.51,141100,0.446906,-0.013307,27.253,40.69,3.087587,2.724341,34,2026-08-21,395.0
628,ABEV3,ABEVH172,CALL,OTM,17.25,15.87,8.695652,0.27,0.28,12300,0.284641,-0.010590,27.648,25.11,1.701323,1.501168,34,2026-08-21,407.0
12620,PETR4,PETRH412,CALL,OTM,40.11,37.89,5.859066,0.89,0.90,71100,0.370182,-0.028172,26.435,33.42,2.348905,2.072563,34,2026-08-21,419.0
12628,PETR4,PETRH422,CALL,OTM,41.11,37.89,8.498285,0.62,0.64,37800,0.279167,-0.024059,27.159,24.75,1.636316,1.443808,34,2026-08-21,422.5
12624,PETR4,PETRH417,CALL,OTM,40.61,37.89,7.178675,0.74,0.76,29200,0.323072,-0.026203,26.488,28.91,1.953022,1.723255,34,2026-08-21,424.0
4476,BBAS3,BBASJ222,CALL,OTM,21.90,19.73,10.998479,0.80,1.37,100,0.308006,-0.008698,29.564,27.01,4.054739,1.689475,72,2026-10-16,425.5
8836,HYPE3,HYPEH227,CALL,OTM,22.32,20.74,7.618129,0.45,0.48,4000,0.363468,-0.018847,29.794,31.63,2.169720,1.914459,34,2026-08-21,429.0
12622,PETR4,PETRH414,CALL,OTM,40.36,37.89,6.518870,0.81,0.83,22900,0.346257,-0.027214,26.611,31.12,2.137767,1.886265,34,2026-08-21,429.0
4474,BBAS3,BBASJ22,CALL,OTM,21.65,19.73,9.731374,0.78,1.44,500,0.345317,-0.009348,36.121,30.54,3.953371,1.647238,72,2026-10-16,430.5
8832,HYPE3,HYPEH220,CALL,OTM,21.82,20.74,5.207329,0.61,0.64,12000,0.431158,-0.020269,35.762,38.12,2.941176,2.595156,34,2026-08-21,434.0
3576,BBAS3,BBASH21,CALL,OTM,21.65,19.73,9.731374,0.25,0.26,50800,0.179690,-0.007809,27.281,16.04,1.267106,1.118035,34,2026-08-21,434.5
4858,BBAS3,BBASL222,CALL,OTM,21.81,19.73,10.542321,1.23,2.01,200,0.438662,-0.009343,24.035,38.39,6.234161,1.612283,116,2026-12-18,444.0
12616,PETR4,PETRH407,CALL,OTM,39.61,37.89,4.539456,1.06,1.07,56800,0.419954,-0.029900,26.700,38.25,2.797572,2.468446,34,2026-08-21,449.5
12618,PETR4,PETRH409,CALL,OTM,39.86,37.89,5.199261,0.97,0.99,46500,0.394775,-0.029071,26.532,35.80,2.560042,2.258861,34,2026-08-21,455.0
3568,BBAS3,BBASH207,CALL,OTM,20.65,19.73,4.662950,0.52,0.54,11300,0.383582,-0.012690,26.584,35.48,2.635580,2.325512,34,2026-08-21,457.0
624,ABEV3,ABEVH167,CALL,OTM,16.75,15.87,5.545054,0.41,0.42,3600,0.389411,-0.012539,28.255,35.09,2.583491,2.279551,34,2026-08-21,469.0
12638,PETR4,PETRH434,CALL,OTM,42.36,37.89,11.797308,0.39,0.41,275200,0.185606,-0.018400,27.542,16.08,1.029295,0.908202,34,2026-08-21,471.0
13278,PETR4,PETRI422,CALL,OTM,41.11,37.89,8.498285,1.01,1.32,9000,0.361550,-0.023688,29.004,31.73,2.665611,1.508836,53,2026-09-18,474.5
3574,BBAS3,BBASH217,CALL,OTM,21.40,19.73,8.464268,0.30,0.32,7500,0.222386,-0.009073,26.552,20.03,1.520527,1.341642,34,2026-08-21,475.0
12630,PETR4,PETRH424,CALL,OTM,41.36,37.89,9.158089,0.57,0.58,16600,0.258544,-0.022945,27.150,22.82,1.504355,1.327372,34,2026-08-21,476.0
3578,BBAS3,BBASH220,CALL,OTM,21.90,19.73,10.998479,0.20,0.22,54300,0.142945,-0.006597,26.302,12.64,1.013685,0.894428,34,2026-08-21,480.5